---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-jwt-php
software:
  - name: byu-jwt-php
    type: Library
    aliases:
    short_description: JWT Decoding and Validation for BYU API
    assignment_group: gro:AD-Front End Technologies and Applications
    notes:
    maintained_by:
      - snelg
      - joshgubler
      - pauldeden
      - eric-nord
      - bwinterton
      - ndpete
      - casture
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/byu-jwt-php
        swagger_urls:
    microservice: false
    technologies_used:
      - PHP
      - Composer
      - Handel-Codepipeline
      - AWS CodeBuild
    stages:
        production:
            hosting_location: Other
            relationships:
                supports:
                    software:
                    service:
    tags:
        data-sensitivity: confidential
        app: byu-jwt-php
        team: gro:AD-Front End Technologies and Applications
