$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-jwt-php
software:
  - aliases:
    assignment_group: gro:AD-Front End Technologies and Applications
    ddd:
      business_domain:
      context_map_url:
      ubiquitous_language_url:
    developed_by_byu: true
    links:
      swagger_urls:
      system_documentation_url: https://github.com/byu-oit/byu-jwt-php
    maintained_by:
      - snelg
      - joshgubler
      - pauldeden
      - eric-nord
      - bwinterton
      - ndpete
      - casture
    microservice: false
    name: byu-jwt-php
    notes:
    short_description: JWT Decoding and Validation for BYU API
    stages:
      production:
        hosting_location: Other
        relationships:
          supports:
            service:
            software:
    tags:
      app: byu-jwt-php
      data-sensitivity: confidential
      team: gro:AD-Front End Technologies and Applications
    technologies_used:
      - PHP
      - Composer
      - Handel-Codepipeline
      - AWS CodeBuild
      - AWS CodePipeline
    type: Library
